common:
  img_topic: "/camera/color/image_raw"
  lid_topic: "/velodyne_points"
  imu_topic: "/bhr_b3/imu"
  leg_topic: "/bhr_b3/foot_state"
  img_en: 0
  lidar_en: 1
  leg_en: 1
  en_auto_mode: false
  gravity_align_en: true
  debug_output_en: false

extrin_calib:
  extrinsic_T: [0.047, 0.01825, 0.41794]
  extrinsic_R: [1, 0, 0, 0, 1, 0, 0, 0, 1]
  Rcl: [-0.010385,-0.999872,-0.0121721,
        0.0215841,0.0119475,-0.999696,
        0.999731,-0.0106446,0.0214573] 
  Pcl: [-0.0151321, -0.105164, -0.0408976]
  extR_urdf2Lid: [1.0, 0.0, 0.0,
                  0.0, 1.0, 0.0,
                  0.0, 0.0, 1.0]

time_offset: 
  lidar_time_offset: -0.1
  imu_time_offset: 0.0
  img_time_offset: 0.0
  leg_time_offset: 0.0
  exposure_time_init: 0.0

preprocess:
  point_filter_num: 3
  filter_size_surf: 0.5
  lidar_type: 2
  scan_line: 16
  blind: 1.5

vio:
  max_iterations: 5
  outlier_threshold: 1000 # 78 100 156 #100 200 500 700
  img_point_cov: 100 # 100 1000
  patch_size: 8
  patch_pyrimid_level: 4
  normal_en: true
  raycast_en: false
  inverse_composition_en: false
  exposure_estimate_en: true
  inv_expo_cov: 0.1

imu:
  imu_en: true
  imu_int_frame: 40
  acc_cov: 0.5 # 0.2
  gyr_cov: 0.3 # 0.5

lio:
  max_iterations: 5
  dept_err: 0.02
  beam_err: 0.05
  min_eigen_value: 0.0025 # 0.005
  voxel_size: 0.5
  max_layer: 2
  max_points_num: 50
  layer_init_num: [5, 5, 5, 5, 5]

kio:
  ankle2sole_model: 0.085
  vel_cnt_cov: [0.2, 0.1, 1.0]
  pos_cnt_cov: 0.05 # 0.05
  en_adapt_cov: true
  height2terr: 0

contact:
  d_raise_thres: 50
  d_conta_thres: 50
  add_contact_det_num: 10 # additional contact det, 5, 10
  d_raise_count_thres: 5
  d_conta_count_thres: 5
  d_swsta_thres: 30 # d < x last y frames, whether addtional contact det. 
  scale_k_sw2st: 4.0 # scale div between stance and swing.
  d_init: false # true: use d_raise to init, false: use foot2gnd to init

local_map:  
  map_sliding_en: false
  half_map_size: 100
  sliding_thresh: 8

publish:
  dense_map_en: true
  pub_effect_point_en: false 
  pub_plane_en: false
  pub_scan_num: 1
  blind_rgb_points: 0.0
  
pcd_save:
  pcd_save_en: false
  filter_size_pcd: 0.15
  interval: -1
  # how many LiDAR frames saved in each pcd file;
  # -1 : all frames will be saved in ONE pcd file, may lead to memory crash when having too much frames.